### ISSUE TITLE
Proposed module hr.course

### ISSUE THREAD

**Issue by FernandoRomera** [OCA/hr#1019]
Hi, @etobella and @jarroyomorales 

In v14.0 i like rename "hr.course" to "hr.course.schedule" and create a new table "hr.course", add this fields in "hr.course": content, descriptions, ...

The relationship of tables would be as follows:
    "hr.course.category" <- "hr.course" <- "hr.course.schedule"

If it's OK with you, I can propose a PR (also migrations directory).

**Comment by etobella** [comment]
Not blocking for me but might be easier to call it hr.course.program this way you don't need to rename the table and might be easier for the migration script. WDYT?

**Comment by FernandoRomera** [comment]
PR #1039
