### ISSUE TITLE
Create new ppe

### ISSUE THREAD

**Issue by ghost** [OCA/hr#1024]
https://github.com/OCA/hr/blob/17ab4ed71bd1545a28d41bd76fca35831b036599/hr_employee_ppe/models/hr_employee_ppe.py#L46

Whe going on menu Employee/PPEs/PPE alocation and clic on create an error occured : 

"Un problème est survenu!
×
hr.employee.ppe(<NewId 0x7fb49c32f198>,).name"
![G6GjfYseNU](https://user-images.githubusercontent.com/8876027/132224851-7d1f7e24-faeb-4e97-b19c-8ee421d654e0.png)

Regards

**Comment by ghost** [comment]
Same issue with fields status

**Comment by TelmoSuarezConinpe** [comment]
You have to set store=True for the fields that contain the compute method.

I have done a PR for migrating this modulo to 14.0 at #1042
