### ISSUE TITLE
[6.1] Fix `hr_interview` dependency on `smtpclient`

### ISSUE THREAD

**Issue by dreispt** [OCA/hr#11]
6.1 tests are failing because:

```
except_orm: (u'Error', u"You try to install module 'hr_interview' that depends
on module 'smtpclient'.\nBut the latter module is not available in your system.")
```

**Comment by bwrsandman** [comment]
Module is from extra addons 
http://bazaar.launchpad.net/~credativ/openobject-addons/extra-6.1/files/head:/smtpclient/

**Comment by dreispt** [comment]
IMO the dependency should be removed. Or at least isolated in a non-OCA module.

**Comment by bwrsandman** [comment]
Will the module work without that deps?

**Comment by dreispt** [comment]
Didn't read the code, but from the description of `smtpclient` I don't see why it shouldn't.
I'm for a quick fix removing the features where the dependency is required.
Probably current Email Templates can do the job, and anyone interested can properly restore them in a later PR.
