### ISSUE TITLE
[V14] hr_public_holidays | No rights applied on buttons

### ISSUE THREAD

**Issue by PureAnthony** [OCA/hr#1130]
## Module
hr_public_holidays

## Describe the bug
The buttons "Approve", "Validate" and "Refuse", visible on many lists, have a "group" attribute, to manage rights.
This attribute gives successfuly the "invisible='1'" on the buttons, but it doesn't do anything, the buttons stay visible anyway...

## To Reproduce
**Affected versions**: 14

1. Log in with a rightless user
2. Create a leave request
3. Go in the list view

**Expected behavior**
No buttons from a rightless user perspective

**Comment by pedrobaeza** [comment]
This has nothing to do with the referred module, so closing.

**Comment by PureAnthony** [comment]
Then where should I post my issue to be helped with hr_holidays_public ??

**Comment by pedrobaeza** [comment]
As said, the module `hr_public_holidays` has nothing to do with rights or the buttons you mention.
