### ISSUE TITLE
How can I use inputs on salary rules?

### ISSUE THREAD

**Issue by EstebanMonge** [OCA/hr#1140]
I am trying to use the inputs on hr_payroll. So for example I created one input on salary rules names description tramo with code 1000.

So in the calculation I put the following code.
if inputs.tramo == 1000:
    result=1000
else:
    result=2000 

But the condition is always false.
## Module
hr_payroll

## Describe the bug
input rules are broken. Always got false on conditions

## To Reproduce
15.0

1. Create a new salary rule
2. Add one input named tramo with code 1000
3. Add to the calculation the following code:
if inputs.tramo == 1000:
    result=1000
else:
    result=2000 
4. Add the salary rule to the salary estructure
5. Create a new payslip for one user and the value of salary rule will be 2000

**Expected behavior**
The value of the salary rule needs to be 1000

**Additional context**
Debian 11

**Comment by pedrobaeza** [comment]
Please do such questions on the Odoo forums. This issue tracker is for handling issues with the modules hosted here (which is not the case for `hr_payroll`).
