### ISSUE TITLE
[14.0][hr_employee_calendar_planning] We cannot create employee from a user

### ISSUE THREAD

**Issue by cvinh** [OCA/hr#1163]
## Module
hr_employee_calendar_planning

## Describe the bug
We cannot create an employee from the user form

## To Reproduce
14.0

1. From a user, click on the button "Create employee"
2. User Error : You can not create employees without any calendar.

**Expected behavior**
The employee can be created and we can add planning afterwards

**Comment by albig** [comment]
We noticed the same error in Odoo 15.0.

**Comment by albig** [comment]
I did some investigation on this issue.

First a screen capture of the problem:

![Odoo - Test User (1)](https://user-images.githubusercontent.com/3354500/234517398-4bb4749f-444b-4d24-adee-003c1900ed9e.png)

The check was introduced with the following commits in August 2022:

* Odoo [14.0] https://github.com/OCA/hr/commit/7d3c2fe9a03c35c084f9a2d9806a6adcb4b84758
* Odoo [15.0] https://github.com/OCA/hr/commit/b217ca530712726453d1dd5fd66fdfaedddf03ef

Of course, I understand the intention of this check. Without `hr_employee_calendar_planning`, the employee record is created and the default calendar from `Settings -> Employees -> Work Organization` are assigend.

![Odoo - New](https://user-images.githubusercontent.com/3354500/234519196-4b51aecf-df53-4461-8413-9608db6f0456.png)

IMHO in case of creating employees from users the tasks to do should be:

1. assign default calendar from global settings
2. auto generate calendar by `hr_employee_calendar_planning`

What do you think, @victoralmau, @pedrobaeza?

**Comment by victoralmau** [comment]
Solved with https://github.com/OCA/hr/pull/1224#issuecomment-1532327677
