### ISSUE TITLE
[odoo 15] [hr_contract_employee_calendar_planning] Cant install this module 

### ISSUE THREAD

**Issue by wangejay** [OCA/hr#1186]
## Module
hr_contract_employee_calendar_planning

## Describe the bug
Cant install this module. it show the error below. 
"Auto generated calendar for employee XXXXXX is used in 1 employee(s) related to another company." 

**Expected behavior**
Can be installed.

**Comment by Saran440** [comment]
you can test and review module `hr_contract_employee_calendar_planning` version15 at here https://github.com/OCA/hr/pull/1182
