### ISSUE TITLE
hr_org_chart_overview is not showing the title of the employees

### ISSUE THREAD

**Issue by noit-arthur** [OCA/hr#1205]
<!-- Provide a general summary of the issue in the Title above.
I installed the module hr_org_chart_overview which is really a great overview of the company.
Unfortunately id dos not show the job title.

## Module
hr_org_chart_overview

## Describe the bug
Instead of showing the job title it shows "false"

## To Reproduce
The version is Odoo 15 and also hr_org_chart_overview 15

1. Create a employee with title
2. Go to the organization chart in reports (as admin)

**Expected behavior**
Instead of the "false" description, I expect the title of the person.

**Comment by chusamo** [comment]
Can you detail more about issue?
 What is the expected result, 
what is the current result 
 how to replicate please?
