### ISSUE TITLE
[15.0] "psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification" when I try to install hr_employee_calendar_planning

### ISSUE THREAD

**Issue by bechiroujii** [OCA/hr#1233]
## Module
**### hr_employee_calendar_planning**

## Describe the bug
When I install the module i get this bug : "psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification"

## To Reproduce
**Affected versions**:15.0

1.install the module

**Comment by Saran440** [comment]
@bechiroujii
I test with new database and it can installable.
May be you can test it again?
