### ISSUE TITLE
Using Repo v14.0 for v16.0

### ISSUE THREAD

**Issue by peebhoiy** [OCA/hr#1275]
**Is your feature request related to a problem?**
This request is in relation to making available some features in the v14 & 15 on v16

**Describe the solution you'd like**
hr_employee_id, hr_employee_birth_name, hr_contract_document, hr_contract_rate, hr_employee_service_contract

**Describe alternatives you've considered**
Non

**Additional context**
It would be helpful if we know using version 14 or 15 on Odoo 16 Community will work effectively.

**Comment by pedrobaeza** [comment]
In general, you shouldn't expect something from other version to work in a version for which is not designed. You can try, but no guarantees for that. Wait for the corresponding migrations, or fund them for speeding up them.
