### ISSUE TITLE
update amounts in timesheet lines after payslip confirmation

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/hr#130]
Hi! We are finalizing a module for 7.0 that will allow to update the timesheet lines for a payslip period, based on the calculated average rate (total payslip amount / total hours worked) and the timesheet lines for that payslip period.

This will make sure that the analytic costs created by the timesheet are updated to match with the actual cost once the employee payslip is confirmed.

Would this module be of interest to OCA?

**Comment by ghost** [comment]
How far do you go with this module ?
How do you manage leaves ?
Do you consider social charges that won't appear on the payslip ?
How do you determine the total payslip amount ? With a payslip line ? If so, it should be configurable.

**Comment by JordiBForgeFlow** [comment]
Hi @dufresnedavid. 

I've been thinking about your questions.... and I'm reconsidering to use this enhancement for now. Mainly because it seems to me that an accurate hourly rate should consider more information, as you described, than I am able to capture in my use case. 

Thanks anyway!
Jordi.
