### ISSUE TITLE
Simple Attendance Integration with Barcode Reader & RaspberryPi

### ISSUE THREAD

**Issue by Nisthulan** [OCA/hr#131]
Hello Community,
I would like to use an easy attendance record system with Odoo.
Instead of using RFID/FingerPrint, Barcode can be considered as a cheap alternative.

My plan is to use an opensource hardware like RaspberryPi connected with
a barcode scanner and, we will run a python script in that, which will read the
inputs from the RaspberryPi, and will communicate with Odoo server via XML-RPC.

I have finished a prototype and it works. I need your valuable suggestions and 
further help to complete it.

Thanks & Regards,
Nisthulan V.K
Dubai, UAE
+971 50 71 61 701
nisthulan@gmail.com

**Comment by tnawut** [comment]
I interested too.
