### ISSUE TITLE
Need for hr_payroll_period

### ISSUE THREAD

**Issue by saltonmassally** [OCA/hr#140]
Hello, I have being looking at working porting several oca/hr addons to 8.0; took a good look at hr_payroll_period and I fail to see remarkable benefits over hr_payslip_run to justify the amount of code and complexity it introduces.

I think going forward we should be concentrating on making hr_payslip_run more usable... what are your thoughts on this?

**Comment by ghost** [comment]
@tarzan0820 hr_payroll_period is a complete mess. Take a look at hr_period instead. I plan on porting it to v8.

**Comment by saltonmassally** [comment]
@dufresnedavid thank you and yes hr_period is way better? When do you think you can port over, if not soon I can take a stab at it and create a PR on which we can work...

**Comment by ghost** [comment]
@tarzan0820 Go ahead, I will assist you. Are you familiar with git filter-branch ? This is required in order to preserve the git history. https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA

**Comment by saltonmassally** [comment]
I will take a look a look at it...
