### ISSUE TITLE
Purpose of struct_id on hr.payslip being editable

### ISSUE THREAD

**Issue by saltonmassally** [OCA/hr#169]
I fail to see the reason why  struct_id field on hr.payslip is editable... changing it definitely has no effect on the rules being computed as the structures are pulled directly from the contract.

I think best case would be for the slip to be computed from the struct_id on the slip as this gives the user the flexibility to override the default struct on the contract... if not it should be made readonly.

I wanted to my thoughts and understand want others think about this

**Comment by ghost** [comment]
@tarzan0820 the onchange would not work otherwise. The value of the field would not be saved to the database.
