### ISSUE TITLE
[hr_worked_days_from_timesheet] - View inheritance may not use attribute 'string' as a selector.

### ISSUE THREAD

**Issue by kossovo** [OCA/hr#171]
Just trying to install <b>hr_worked_days_from_timesheet</b> module in Odoo 9.0 version. I got the following error:

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `hr.payslip.form`
[view_id: 615, xml_id: n/a, model: hr.payslip, parent_id: 363]
None" while parsing /home/clovis/Documents/odoo9/hr-addons/hr_worked_days_from_timesheet/hr_payslip_view.xml:4, near
<record id="view_hr_payslip_form" model="ir.ui.view">
            <field name="name">hr.payslip.form</field>
            <field name="model">hr.payslip</field>
            <field name="inherit_id" ref="hr_payroll.view_hr_payslip_form"/>
            <field name="arch" type="xml">
                <data><separator string="Worked Days" position="replace"/>
                <field name="worked_days_line_ids" position="before">
                    <group>
                        <separator string="Worked Days"/>
                        <div class="oe_right oe_button_box">
                            <button string="Import from Timesheets" name="import_worked_days" type="object" states="draft"/>
                        </div>
                    </group>
                </field>
            </data></field>
        </record>

**Comment by ghost** [comment]
@kossovo Just let you know that actually no hr module has been ported to v9. hr_worked_days_from_timesheet is not even ported to v8.

**Comment by acysos** [comment]
Hello,

I have this module ported and refactored to v8. I will put a PR today. I expect that the other PR that I have will be merge asap.

Greetings

**Comment by kossovo** [comment]
+1

2015-11-05 12:51 GMT+01:00 Odoo - OpenERP - Acysos S.L. <
notifications@github.com>:

> Hello,
> 
> I have this module ported and refactored to v8. I will put a PR today.
> 
> Greetings
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/hr/issues/171#issuecomment-154039683.

## 

_Clovis NZOUENDJOU_
_Développeur Python/Odoo_

http://anybox.fr

**Comment by acysos** [comment]
Hello,

The PR has done https://github.com/OCA/hr/pull/189

Greetings
