### ISSUE TITLE
Audit modules in hr

### ISSUE THREAD

**Issue by bwrsandman** [OCA/hr#18]
Some of the code in hr is of poor quality and their uses are questionable
- Very long functions
- Multiple classes in same script
- Very long lists of columns added to models
- Unclear usage
- Lack of tests
## Suggested Action Plan
1. [x] Fix style errors with #17 
2. [x] Fix build errors
3. [ ] Do the refactoring with the port to v8, keeping the old API - Audit and review
4. [ ] Backport enhancements without v8 specific changes to v7
5. [ ] Port v8 to new API
## Modules
- [ ] hr_accrual
- [ ] hr_contract_init
- [ ] hr_contract_reference
- [ ] hr_contract_state
- [ ] hr_department_sequence
- [ ] hr_emergency_contact
- [ ] hr_employee_education
- [ ] hr_employee_firstname
- [ ] hr_employee_id
- [ ] hr_employee_legacy_id
- [ ] hr_employee_phone_extension
- [ ] hr_employee_seniority
- [ ] hr_employee_state
- [ ] hr_experience
- [ ] hr_family
- [ ] hr_holidays_extension
- [ ] hr_infraction
- [ ] hr_job_categories
- [ ] hr_job_hierarchy
- [ ] hr_labour_recruitment
- [ ] hr_labour_union
- [ ] hr_language
- [ ] hr_payroll_extension
- [ ] hr_payroll_period
- [ ] hr_payroll_register
- [ ] hr_payroll_register_report
- [ ] hr_payslip_amendment
- [ ] hr_policy_absence
- [ ] hr_policy_accrual
- [ ] hr_policy_group
- [ ] hr_policy_ot
- [ ] hr_policy_presence
- [ ] hr_public_holidays
- [ ] hr_report_manpower
- [ ] hr_report_payroll_attendance_summary
- [ ] hr_report_payroll_net
- [ ] hr_report_turnover
- [ ] hr_resume
- [ ] hr_schedule
- [ ] hr_security
- [ ] hr_simplify
- [ ] hr_skill
- [ ] hr_transfer
- [ ] hr_wage_increment
- [ ] hr_webcam

**Comment by dreispt** [comment]
IMO this work should mostly be done in parallel with the port to v8.

My suggested action plan:
  1) Customize the v7 repo TravisCI to ignore style errors. 
  2) Fix v7 build errors ASAP to get TravisCI green
  3) Do the refactoring with the port to v8, keeping the old API
  4) And then backport the refactoring to v7.

**Comment by bwrsandman** [comment]
I would replace 1) with finishing #17 I'm about half way through and I intend to finish.
I would then add 5) use new api for v8

I problem I see is the changes we will have to do for v8 wont all be back-portable (i.e. changes to xpaths)
