### ISSUE TITLE
[hr_worked_days_from_timesheet] Compatibility with existing working schedule

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/hr#187]
Hello,

I want to use the employee's working schedule as a tool to validate that the employee complete their timesheets in line with their contract schedule. 

But I don't want the working schedule to automatically fulfill the payslip. Instead, I want to fulfill the payslip based on the timesheet hours.

I am trying to use module "hr_worked_days_from_timesheet" together with contracts that have an existing working schedule, but Odoo will then import both the worked hours from timesheets AND the worked hours as per the contract's working schedule.

The reason to import hours from timesheets is that different analytic accounts derive different salary categories, and different accounts. For example, time reported on an overhead analytic account will drive the allocation to an expense GL account, whereas time reported on a project-related analytic account will drive the allocation of the salary to a COGS GL Account.

My proposal would be that module "hr_worked_days_from_timesheet" disables the computations of get_worked_day_lines on hr.payslip, so that the only worked hours derived from the payslip will come from the timesheet.

What do you think about it?

**Comment by andhit-r** [comment]
@jbeficent I agree with your proposal. I also need to import timesheet summary into payslip work days. But i am not so sure about removing get_worked_day_lines computations since it may used by salary rules computation. So i suggest to leave it be and add timesheet summary value.

**Comment by andhit-r** [comment]
This module currently still WIP to migrate to 8.0. After it migrate I will add this feature into this module.
