### ISSUE TITLE
patch disappeared from hr_payroll_extension: is that intentional?

### ISSUE THREAD

**Issue by diassynthesis** [OCA/hr#19]
Is the hr_payroll patch no longer needed for V7.0 ?

**Comment by dreispt** [comment]
Could you be more specific?

**Comment by diassynthesis** [comment]
For V7.0, on 09/28/2013 the folder "patches" under "hr_payroll_extension" was deleted.

**Comment by dreispt** [comment]
That 's commit https://github.com/OCA/hr/commit/a314d8ec9377472fd4d50888718defe3c1668de4 by @max3903 .
Maybe he can help.

**Comment by diassynthesis** [comment]
I understand that the folder "patches" does not have its place in the OpenERP's Module Folder Structure.
What i want to know is, if the patch is still necessary to make  the module work properly, this should be at least,  clearly indicated in the manifest file (@ the 'description' section), and put a link to the patch file.

**Comment by lepistone** [comment]
Hi @max3903. Was that patch removed intentionally in https://github.com/OCA/hr/commit/a314d8ec9377472fd4d50888718defe3c1668de4 or is it a faulty merge? Thanks!

**Comment by dreispt** [comment]
@bwrsandman @max3903 Was the patch obsolete?

**Comment by bwrsandman** [comment]
I can't speak as to why it was deleted, but I don't see why the changes in the patch couldn't be done as a module...

We should not encourage patching the server.

**Comment by dreispt** [comment]
@diassynthesis Do you think we can close this?

**Comment by diassynthesis** [comment]
Not yet please. I've posted a message at http://miketelahun.wordpress.com and i'm waiting for a reply

**Comment by dreispt** [comment]
If @miketelahun should comment on this, it's best to just mention him as I just did.
I've just reviewed the diff, it's related to the "Need Action" mechanism, not to HR or Payroll.

So it definitely shouldn't be in the module.
I guess I can answer your question: it's not needed.

**Comment by diassynthesis** [comment]
@dreispt Yes, you can close this issue. Just another question (not directly related to this branch, but related to the hr_payroll module): Could you please take a look at https://github.com/odoo/odoo/issues/3916 and tell me what you think about the last lines of the "hr_payroll-hr_payroll.patch".Thank you and best regards.
NB: The related patch is "hr_payroll-hr_payroll.patch"and not the "openobject-server-openerp-addons-base-ir-ir_ui_menu.patch".

**Comment by miketelahun** [comment]
The file removed in a314d8e is not necessary, as it relates to a useability improvement for ir.need_action

**Comment by diassynthesis** [comment]
Thank you, but are you talking about "openobject-server-openerp-addons-base-ir-ir_ui_menu.patch" or "hr_payroll-hr_payroll.py-patch", or both.

**Comment by miketelahun** [comment]
I am talking about openobject-server-openerp-addons-base-ir-ir_ui_menu.patch

**Comment by diassynthesis** [comment]
What about the "hr_payroll-hr_payroll.py-patch".

**Comment by diassynthesis** [comment]
Still waiting for a response about "hr_payroll-hr_payroll.py-patch".                                                        About https://github.com/odoo/odoo/issues/3916 , solved but !!! a new bug revealed  https://github.com/odoo/odoo/issues/4363

**Comment by dreispt** [comment]
OCA modules shouldn't have bug patches in them. 

If you have a bug, open an Odoo issue. For community maintained patches, look at the OCA/OCB project. You can also file the Issue there, but I believe an OCB PR would also be expected. In case you are not able to provide a fix yourself, my honest advice is to seek expert help.

This issue should be closed, since bug fixes are out of scope for OCA modules.

**Comment by diassynthesis** [comment]
@dreispt That's what I've said in my third comment. I will close this issue at the end of this comment. @miketelahun I just want to know, if the "hr_payroll-hr_payroll.py-patch" is  needed or not ?             Thank you and best regards.
