### ISSUE TITLE
Lost return value

### ISSUE THREAD

**Issue by Garamotte** [OCA/hr#223]
I'm grepping community addons to search for a bug I found in the base module.

There is one occurence of this bug in this repository :
https://github.com/OCA/hr/blob/8.0/hr_employee_firstname/models/hr_employee.py#L39

See my PR on Odoo : https://github.com/odoo/odoo/pull/11985

**Comment by dreispt** [comment]
That method does not have a `return` statement, so the super return value is irrelevant.
So no bug there.

**Comment by Garamotte** [comment]
The `_auto_init` method returns the list of stored computed fields to recompute and store in the database :
https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L2706

When the super return value is forgotten, computed fields added in the model will not be computed for existing records during the module update.

**Comment by dreispt** [comment]
OK. Maybe the issue is deeper: the module should be using an init hook instead of extending `_auto_init`.

**Comment by Garamotte** [comment]
I agree, this would be better. There is the `init` method for that.

That method is called if exists on v8/v9, and always exists on master (future v10).
- v8/v9 : https://github.com/odoo/odoo/blob/9.0/openerp/modules/module.py#L296-297
- v10 : https://github.com/odoo/odoo/blob/master/openerp/models.py#L2851-2855
