### ISSUE TITLE
Recreate v9 branch from v8

### ISSUE THREAD

**Issue by feketemihai** [OCA/hr#238]
@OCA/human-resources-maintainers 

@dreispt I was talking about the recreation of v9 branch from v8 branch, when v9 branch was created only 22 modules were migrated to v8, since then there has been a lot of modules ported to v8, which were done in the new api, and little bug fixed done in v8, removal of modules dependant of Aeroo, plus translations from Transifex. Since all this has been done in v8, and v9 branch, for the momment doesn't have any module ported, i thougth it's a good moment to recreate the v9 branch from v8 branch, and will be more easier at migration of the modules already done in v8, since we will have to review only adaptation to v9, not all the process of migration, tests, new api, it will reduce the time reviewing the port to v9.

I am waiting your opinion and i don't exactly no if OCA has a tool for this, and if not i can create a PR that will make all v8 modules Not Instalable and overwrite V9 branch.

**Comment by dreispt** [comment]
I see. Given that v9 has no ported modules yet, that makes sense.
The `installable` flag might need some work, but other than that git should be enough to take care of this. A single PR would be fine for me.

**Comment by feketemihai** [comment]
@dreispt Ok...i will do it on monday morning. Thanks.

**Comment by pedrobaeza** [comment]
Use https://github.com/OCA/maintainer-tools/blob/master/tools/migrate_branch.py for that or I can do it if you prefer.

**Comment by feketemihai** [comment]
@pedrobaeza I didn't use it before...so if you can do it i'll prefer that and i will do the pr on monday...not in the office untill then. Thanks.

**Comment by feketemihai** [comment]
Sorry...i just saw that already sets instalable to False...no need for extra pr...
