### ISSUE TITLE
there is a branch master, while 8.0 is full of unported modules

### ISSUE THREAD

**Issue by lepistone** [OCA/hr#24]
I imagine 8.0 should be deleted, and master renamed 8.0. What do you think @dreispt? I can do that myself if you agree.

**Comment by dreispt** [comment]
Ouch! I totally agree. It would be great if you could do that.

**Comment by pedrobaeza** [comment]
Yeah, you should do the move to `__unported__` dir and put installable flag to false, and then make 8.0 the default branch, deleting the master one, because master doesn't contain the PEP8 fix.

**Comment by dreispt** [comment]
I now see what happened: https://github.com/OCA/hr/pull/22 was made against `master` because I didn't realize `8.0` was not the default branch yet!
It's best to delete `8.0` and rename `master`.

**Comment by pedrobaeza** [comment]
But master branch doesn't have PEP8 applied. Diffs are going to be contaminated with PEP8 + migration. I prefer to start from 8.0 branch and cherrypick https://github.com/dreispt/hr/commit/5ad7a4e33344759d270d0b71890a7f8242db79f7

**Comment by dreispt** [comment]
OK.

**Comment by pedrobaeza** [comment]
8.0 branch is now updated. We should remove master and make 8.0 the default one.

**Comment by lepistone** [comment]
@pedrobaeza: thanks, @gurneyalex set the default branch to 8.0
