### ISSUE TITLE
ensure_one() error op benefit_rate

### ISSUE THREAD

**Issue by RichDijk** [OCA/hr#245]
We have installed this module but do get an error after applying a benefit rule when opening a contract or opening employee benefit rates.

error:

>   return new_api(self, _args, *_kwargs)
>   File "/opt/odoo/custom/community_addons/hr_employee_benefit/models/hr_employee_benefit_rate.py", line 110, in get_amount
>     self.ensure_one()
>   File "/opt/odoo/odoo-server/openerp/models.py", line 5303, in ensure_one
>     raise except_orm("ValueError", "Expected singleton: %s" % self)
> except_orm: ('ValueError', 'Expected singleton: hr.employee.benefit.rate(1, 2)')

What is the best way to fix this?

**Comment by ghost** [comment]
@RichDijk what version of Odoo are you using

**Comment by RichDijk** [comment]
@dufresnedavid  , we use Odoo 8

We have already tried the following fix which looks ok after small tests:

```
@api.multi
def _get_amounts_now(self):
    today = context_today(self)
    for rate in self:
        rate.employee_amount = rate.get_amount(today)
        rate.employer_amount = rate.get_amount(today, employer=True)

@api.multi
def get_amount(self, date, employer=False):
    for rate in self:
        for line in rate.line_ids:
            if line.date_start <= date and (
                not line.date_end or date <= line.date_end
            ):
                return (
                    line.employer_amount if employer else
                    line.employee_amount
                )
    return False
```

**Comment by RichDijk** [comment]
Fix works properly.
