### ISSUE TITLE
[8.0,9.0] hr_recruitment_partner doesn't work with fetchmail creating

### ISSUE THREAD

**Issue by intero-chz** [OCA/hr#255]
Hi,

after installing hr_recruitment_partner you can't use fetchmail server to create `hr.applicant` anymore, because Odoo tries to create an empty partner, which won't work (name -> NULL).

So either the module should create a partner on its own in `hr.applicant` message_new() or the module should state, that it isn't possible to use the feature while installed.

Best Regards

**Comment by intero-chz** [comment]
@dreispt I'm pinging you, because i don't know who is responsible for the `hr` repo.

I would create a pull request, but the question is: what solution should be chosen. I've mentioned two solutions, but maybe there are some interesting other ones?

**Comment by dreispt** [comment]
I see, the module makes the `parter_name` field mandatory.
IMO the sensitive thing to do is to add a default value to `partner_name`.
Since the Application title, `name` is mandatory, I would suggest for `partner_name`to use it's value as a default.
Do you think you can make a PR for this?

**Comment by intero-chz** [comment]
`partner_name` is already set by the origin `message_new` (by email from value). Are default values working for related fields at all?

**Comment by dreispt** [comment]
You're not using any default values then.
`partner_name` is a related field, and it gets it's value written on the Partner `name`.
It doesn't make sense that you get an error.
Can you give a link to the `message_new()` code you refer to?

**Comment by intero-chz** [comment]
https://github.com/odoo/odoo/blob/8.0/addons/hr_recruitment/hr_recruitment.py#L386

**Comment by dreispt** [comment]
AFAICS the `message_new`is writing both on `name` and `partner_name`.
You shouldn't have any error then. 😕 
Do you have a traceback of the error you can share?

**Comment by dreispt** [comment]
Ping!

**Comment by intero-chz** [comment]
Pong (sorry, was on vacation):

> Traceback (most recent call last):
>   File "workspace/odoo/addons/fetchmail/fetchmail.py", line 215, in fetch_mail
>     context=context)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/addons/mail/mail_thread.py", line 1204, in message_process
>     thread_id = self.message_route_process(cr, uid, msg_txt, msg, routes, context=context)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/addons/mail/mail_thread.py", line 1124, in message_route_process
>     thread_id = model_pool.message_new(cr, user_id, message_dict, custom_values, context=nosub_ctx)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/addons/hr_recruitment/hr_recruitment.py", line 405, in message_new
>     return super(hr_applicant, self).message_new(cr, uid, msg, custom_values=defaults, context=context)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/addons/mail/mail_thread.py", line 1240, in message_new
>     res_id = model_pool.create(cr, uid, data, context=context)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/addons/hr_recruitment/hr_recruitment.py", line 419, in create
>     obj_id = super(hr_applicant, self).create(cr, uid, vals, context=context)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/addons/mail/mail_thread.py", line 381, in create
>     thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/openerp/api.py", line 345, in old_api
>     result = method(recs, _args, *_kwargs)
>   File "workspace/odoo/openerp/models.py", line 4092, in create
>     record = self.browse(self._create(old_vals))
>   File "workspace/odoo/openerp/api.py", line 248, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "workspace/odoo/openerp/api.py", line 481, in new_api
>     result = method(self._model, cr, uid, _args, *_kwargs)
>   File "workspace/odoo/openerp/models.py", line 4148, in _create
>     record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/openerp/api.py", line 345, in old_api
>     result = method(recs, _args, *_kwargs)
>   File "workspace/odoo/openerp/addons/base/res/res_partner.py", line 573, in create
>     partner = super(res_partner, self).create(vals)
>   File "workspace/odoo/openerp/api.py", line 248, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "workspace/odoo/openerp/api.py", line 481, in new_api
>     result = method(self._model, cr, uid, _args, *_kwargs)
>   File "workspace/odoo/addons/mail/mail_thread.py", line 381, in create
>     thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
>   File "workspace/odoo/openerp/api.py", line 250, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "workspace/odoo/openerp/api.py", line 345, in old_api
>     result = method(recs, _args, *_kwargs)
>   File "workspace/odoo/openerp/models.py", line 4092, in create
>     record = self.browse(self._create(old_vals))
>   File "workspace/odoo/openerp/api.py", line 248, in wrapper
>     return new_api(self, _args, *_kwargs)
>   File "workspace/odoo/openerp/api.py", line 481, in new_api
>     result = method(self._model, cr, uid, _args, *_kwargs)
>   File "workspace/odoo/openerp/models.py", line 4230, in _create
>     tuple([u[2] for u in updates if len(u) > 2])
>   File "workspace/odoo/openerp/sql_db.py", line 158, in wrapper
>     return f(self, _args, *_kwargs)
>   File "workspace/odoo/openerp/sql_db.py", line 234, in execute
>     res = self._obj.execute(query, params)
> IntegrityError: null value in column "name" violates not-null constraint
