### ISSUE TITLE
HR_EXPENSE_INVOICE - error when try to "generate Accounting Entries"

### ISSUE THREAD

**Issue by yboujraf** [OCA/hr#257]
**Odoo Version : 8
Module : HR_EXPENSE_INVOICE
ERROR MESSAGE : "Cannot reconcile supplier invoice payable with generated line. Please check amounts and see if the invoice is already added or paid. Invoice: False"**

For some expenses where I am trying to link with an invoice, we have this error message.
We have verified if the amout of the invoice is the same as the expense and it is.

**Question :** if we need to uninstall the module installed in our server and update it by a new one. What's happening about all the expenses allready reconiled with an invoice?

I am stopped now and need to close our quarter.

Best Regards,
Youssef

**Comment by pedrobaeza** [comment]
The message is for a line where there's no invoice, so this doesn't seems to be with the module itself.

**Comment by yboujraf** [comment]
Dear,

What I suspect is when I selecting an invoice, the reference assigned by the expense module is wrong.

![image](https://cloud.githubusercontent.com/assets/6151258/19019889/413da100-8897-11e6-8eff-ea886b5dac61.png)

We have the REFERENCE : EXJ/2015/0087

When assigned in the expense, we have 👍 

![image](https://cloud.githubusercontent.com/assets/6151258/19019892/58fa1044-8897-11e6-919f-58841db81b31.png)

INVOICE : EXJ/2015/0087 BE131006253

I don't know where is coming this extra data because in the invoice we don't have anywhere this reference.

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear,

Just to inform you we have found the issue.
When we remove the INVOICE REFERENCE from the Invoice from the expense and reconcile the invoice in the journal entries, all work fine.

To fix the issue, is it possible to have more details in the log or some where to identify the issue.

Best Regards,
Youssef
