### ISSUE TITLE
[8.0] hr_holidays_legal_leave

### ISSUE THREAD

**Issue by yelizariev** [OCA/hr#265]
This commit
41c3beb178c47461be117ed43a34af6dcb9298f0
has to be fixed, because computed field can be called with multiple records https://github.com/OCA/hr/pull/262#issuecomment-253496780

patch for 10.0: https://github.com/OCA/hr/pull/262/commits/a75cdc8c252e5ced6fafc2bc1fa61e352debdb26

cc @feketemihai

**Comment by feketemihai** [comment]
@yelizariev Thanks for found this, i never had problems with it...should we patch the inverse method as well?

**Comment by pedrobaeza** [comment]
Closing as there's a PR

**Comment by yelizariev** [comment]
@feketemihai Not sure about reverse method. Probably, it's needed if someone will import employees table with new remaining leaves value

**Comment by yelizariev** [comment]
We face this issue, when click on some employees in dashboard
