### ISSUE TITLE
Recruitment Partner data should have security access rules

### ISSUE THREAD

**Issue by dreispt** [OCA/hr#287]
The `hr_recruitment_partner` module saves Applicant personal data into Partners.
But this data is available to all users.
Since personal data is protected by data privacy regulations, only selected users should be able to access that information.

I believe we need a "Personal data" flag on Partners, and security rule on it so that only selected users can see it. By default, HR Officers would have this access.
Partners related to Applicants and Employees should have this flag enabled by default.

Thoughts?

**Comment by pedrobaeza** [comment]
Better to protect it with a group and a view linked to that group. Only those with that group will be able to see that data, but the rest can see basic information.

**Comment by dreispt** [comment]
@pedrobaeza  if I understand correctly, that would be just GUI superficial security.
And the Applicant Partner record would still be selectable in other Many2ones, and IMO that is a problem...

**Comment by pedrobaeza** [comment]
Uhm, you're right about that GUI security, but I don't see a problem about the many2one selectable thing. I prefer to have that selectable for certain operations (like for example, sending a message), but the problem here is about certain information inside their data.

Can you put groups security at field level?

**Comment by dreispt** [comment]
> Can you put groups security at field level?

Yes, a similar issue was raised about Employee personal data, and Olivier's fix was to add group security at field level.
