### ISSUE TITLE
[8.0][REF][hr_holidays] Holidays advanced

### ISSUE THREAD

**Issue by moylop260** [OCA/hr#29]
We will make a module that add holidays validations.
*As max days of holidays.
*Compute number total of holidays (without free days or weekend).
*Payment of holidays

Is a good idea make a PR here?

**Comment by yvaucher** [comment]
As there is https://github.com/OCA/hr/tree/7.0/hr_holidays_extension
in this branch, this is the right place.

**Comment by bwrsandman** [comment]
This is the right place. Take a look in `__unported__` to see if such a module already exists.

**Comment by moylop260** [comment]
Ok, I got it
Thank you
