### ISSUE TITLE
[Question][hr_working_hours] REF to detect delays and overtimes

### ISSUE THREAD

**Issue by moylop260** [OCA/hr#32]
Hello OCA team,
Anybody know a module that allow detect delays and overtimes of employee based on "working hour" configuration of his hr.contract?

**Comment by dreispt** [comment]
I guess not.

**Comment by pedrobaeza** [comment]
I don't know also.

**Comment by ghost** [comment]
hi @moylop260, I don't think there is a module like this. But you could easily make it by adding one field in the 'resource.calendar.attendance' model.

**Comment by eLBati** [comment]
Hi @moylop260 didn't hr_attendance_analysis do the job?
https://github.com/OCA/hr-timesheet/tree/8.0/hr_attendance_analysis

**Comment by feketemihai** [comment]
Probably you can use hr_overtime module, 
https://github.com/Asmaa-Aly/hr_overtime
that have a report and is computed in payslip, even that the module still needs some adjustments: acces rigths...
