### ISSUE TITLE
public holidays doesnt work

### ISSUE THREAD

**Issue by sertrah** [OCA/hr#353]
i'm currently used this module for generate the holidays in my country, but doesnt work becouse the calculate its wrong, must be 3 days and no 4 days if i have activate the public holiday.
i tried removing work schedules to see if that was the problem But no change was seen
![image](https://user-images.githubusercontent.com/20744476/28473335-bd54fbfa-6e09-11e7-8a54-ba720561160d.png)
and this how i configurate the  holiday
![image](https://user-images.githubusercontent.com/20744476/28473368-d952fcda-6e09-11e7-8671-4c1c5d8046cb.png)
I hope you can help me please
Thanks!

**Comment by pedrobaeza** [comment]
The module itself doesn't do that part. See https://github.com/OCA/hr/tree/10.0/hr_holidays_compute_days
