### ISSUE TITLE
public holidays year

### ISSUE THREAD

**Issue by JanisJanis** [OCA/hr#360]
v10.0

Module:
hr_public_holidays

Any new public holidays.

Current view:
![image](https://user-images.githubusercontent.com/7612247/29110553-a992d76e-7cef-11e7-8a86-1a99f5db3fb7.png)

Expected behavior:
Year format without spaces and comma:
2017

**Comment by Smined** [comment]
Am trying to change the same but not able to , please help.

**Comment by Martronic-SA** [comment]
Hi,
You can add `widget="text"` to your view definition:
`<field name="year" widget="text"/>`
