### ISSUE TITLE
Migrating modules starting from 9

### ISSUE THREAD

**Issue by feketemihai** [OCA/hr#397]
Hello all,

since there were some improvements to Odoo base code regarding HR, Holidays, Expenses modules, before migration the modules from version 8.0,(even if it's to 9.0,10.0,11.0), we should check was is changed in the base code, not to duplicate working methods.

I suggest that we consolidate modules that only add one field, into a more generic one, to be able to maintain the repository more easy. We can add in this issue all the modules that should be deprecated/consolidated into new ones, so people to know what it should be migrated and how.

**Comment by feketemihai** [comment]
@OCA/human-resources-maintainers

**Comment by dreispt** [comment]
> I suggest that we consolidate modules that only add one field, into a more generic one, to be able to maintain the repository more easy. 

Yes, absolutely.

> We can add in this issue all the modules that should be deprecated/consolidated into new ones, so people to know what it should be migrated and how.

We already have https://github.com/OCA/hr/issues/157 for that, I suggest to use it.
I see you are a member on the HR Maintainers. so you can edit the Issue's text there to update the plan.

**Comment by pedrobaeza** [comment]
Should we keep this opened?
