### ISSUE TITLE
Do we need  hr_holidays_notify_employee_manager (can be done with automated actions)

### ISSUE THREAD

**Issue by yung-wang** [OCA/hr#426]
Dear OCA,

I wonder if we really need this module:
[https://github.com/OCA/hr/tree/10.0/hr_holidays_notify_employee_manager](https://github.com/OCA/hr/tree/10.0/hr_holidays_notify_employee_manager)

Since you can do the same with an automated action + email template.

**Comment by feketemihai** [comment]
@yung-wang I tend to leave it as a module, since not all users are technical enough to do this, so it will help...

**Comment by yung-wang** [comment]
ok.
