### ISSUE TITLE
hr_public_holidays

### ISSUE THREAD

**Issue by nedaszilinskas** [OCA/hr#454]
### Module(s)
hr_public_holidays [10.0]

Return type is not consistent in method _get_holidays_list(...)_.
If empty it returns list instead of empty recordset (https://github.com/OCA/hr/blob/10.0/hr_public_holidays/models/hr_public_holidays.py#L95) which I assume is expected since we have @api.returns('hr.holidays.public.line').

**Comment by pedrobaeza** [comment]
@feketemihai you were the author. Can you tell us?

**Comment by feketemihai** [comment]
@nedaszilinskas @pedrobaeza I really don't remember, it was a fast continuation of another non finished PR...and from 2 years ago...and moule is migrated like this in v9 and v10.

Will check when i have more time, but by default it should be an empty recordset.

**Comment by nedaszilinskas** [comment]
@pedrobaeza @feketemihai thank you, I just needed confirmation that this is considered an issue. I will make a PR for this fix if you do not mind?

**Comment by feketemihai** [comment]
@nedaszilinskas It's an issue and it's present starting from v8..

**Comment by pedrobaeza** [comment]
Please make the PR

**Comment by pedrobaeza** [comment]
Fixed in #455
