### ISSUE TITLE
[8.0] hr_employee_data_from_work_address: Access error on ir.property when deleting partner

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/hr#473]
Some users in a system do not have deletion rights for `ir.property`, and thus deleting a partner fails [here](https://github.com/OCA/hr/blob/8.0/hr_employee_data_from_work_address/models/hr_employee.py#L90).

Still investigating this. @hbrunn any insights? Possible solutions include:

1. Investigating which property fails to be deleted and creating an exception for this
2. Using `sudo` to force-delete the partner
3. Deactivating the partner instead of deleting

**Comment by hbrunn** [comment]
I think we'll be best off with (3) as deleting properties is a thing for user managers: https://github.com/OCA/OCB/blob/8.0/openerp/addons/base/security/ir.model.access.csv#L28-L29

Let's do it the python way and catch an access exception when deleting, then deactivate the partner (possibly log a note?) and if that throws too, log a warning in the log
