### ISSUE TITLE
hr_holiday_public V11

### ISSUE THREAD

**Issue by johnbangad** [OCA/hr#528]
is there a way that the color on holiday will be back because on version 10 we can config from system parameters to highlights the holidays. But in v11 it was removed.

**Comment by pedrobaeza** [comment]
Can you be more specific?

**Comment by johnbangad** [comment]
I was reffering to this config from v10 

To customize the color to highlight public holidays in calendar views:

navigate to Settings > Technical > System parameters
provide a value to calendar.public_holidays_color key (both hex RGB and valid web color names will do, and invalid color settings would be ignored completely).

then the new version v11, I don't see this.

**Comment by pedrobaeza** [comment]
That option is not migrated. Feel free to port the PR #477 to v11
