### ISSUE TITLE
Validation Error in hr_public_holidays module v11

### ISSUE THREAD

**Issue by burhan-vakharia** [OCA/hr#569]
Odoo Version - v11 Community

1) Create a new Public Holiday.
2) Add a new Public holiday line.
3) Select the date, add name and untick the Date may change Boolean.

Now try to save the Public Holiday, it will give a Validation Error - Screenshot Link - https://prnt.sc/mzviim .

Video URL - https://nimb.ws/BGXD7x

**Comment by nikul-serpentcs** [comment]
@pedrobaeza @mreficent Can you please check it?

**Comment by SSanfilippo** [comment]
Hi, have any feedback about this error? Also I cannot use the module for odoo 11 for same problem of burhan.

Best regards,
Simone

**Comment by moylop260** [comment]
@SSanfilippo @nikul-serpentcs @burhan-vakharia 
Could you check the following fix https://github.com/OCA/hr/pull/590 from @luistorresm, please?

**Comment by SSanfilippo** [comment]
Hi, I update the module on my enviroment, but I have always the error.

The reference of my error is: [oggetto con referenza: date - date]

**Comment by luistorresm** [comment]
Hello @SSanfilippo 

You have updated the module? In your Odoo instance?

**Comment by SSanfilippo** [comment]
Yes @luistorresm, I had downloaded the source from github, then I extract in my addons folder the hr_public_holidays folder.
I check also if the two modified files are presents, and yes are modified.

**Comment by luistorresm** [comment]
Maybe is missing make -u hr_public_holidays or in the apps update manually the module, because was changed the view.

Regards

**Comment by SSanfilippo** [comment]
I make the update manually, better I restart odoo service then as developer mode update all apps.
I use windows version, probably forgot a step?

**Comment by luistorresm** [comment]
Yes @SSanfilippo 

Please open the apps view and search `hr_public_holidays`, open  it and press `Update`

**Comment by SSanfilippo** [comment]
Hi, good news (and sorry for my forgotten operation).
I update the module in apps and later public holiday work fine.

**Comment by luistorresm** [comment]
Hello @moylop260 @max3903 

Could be closed this ticket?

Regards

**Comment by SSanfilippo** [comment]
Hi at all,
probably in Odoo 12 there is the same problem.

![image](https://user-images.githubusercontent.com/17512851/71314703-a656a780-244d-11ea-891a-5c04855b7ca5.png)
