### ISSUE TITLE
[11.0] hr_holidays_compute_days error

### ISSUE THREAD

**Issue by glauco70** [OCA/hr#578]
There is a problem in hr_holidays_compute_days module, if I check the "Full day" before inserting a date I have this error in _inverse_date_to_full (and in  _inverse_date_from_full also) : 
**dt = fields.Datetime.from_string(record.date_to_full).replace(
AttributeError: 'NoneType' object has no attribute 'replace'**

I resolve inserting this if : 
_if record.date_to_full:_
before the line indicated

**Comment by pedrobaeza** [comment]
How do you get that situation? Can you do a PR with the solution?

**Comment by glauco70** [comment]
> How do you get that situation?

I create a hr.holidays request and I check the "Full Day" check box before inserting the date_from or date_to.

> Can you do a PR with the solution ?

Yes

**Comment by hugho-ad** [comment]
this can be closed

**Comment by moylop260** [comment]
fixed from https://github.com/OCA/hr/pull/579
