### ISSUE TITLE
hr_employee_firstname: error when filling only lastname

### ISSUE THREAD

**Issue by luismontalba** [OCA/hr#580]
When hr_employee_firstname is installed you fill a firstname and a lastname when creating a new employee. Only the lastname is mandatory but if the firstname is not filled an error occurs. This problem has been detected in V11 but it comes from previous versions.

**Comment by astirpe** [comment]
Fixed by https://github.com/OCA/hr/pull/583 for V11.
The porting to V12 (https://github.com/OCA/hr/pull/577) includes the fix.

**Comment by astirpe** [comment]
This issue can be closed
