### ISSUE TITLE
Question about hr_expense_invoice

### ISSUE THREAD

**Issue by kittiu** [OCA/hr#585]
Hi, as I am about to migrate hr_expense_invoice to v12. In my opinion I feel the workflow of using this module is not quite smooth (my opinion, can be wrong). So I want to open for discussion, please correct me.

From my understanding, this module is used in case the employee got the supplier tax invoice from vendor, and back to office to reimburse the amount (tax need to goes to the vendor)

AS-IS: Invoice before expense
1. Employee buy multiple service/items from and got the Tax Invoice from Vendor.
2. To reimburse, the employee must hand over Supplier Tax Invoice to the accountant.
3. Accountant will create vendor bill and confirm it to issue the invoice number, i..e, BILL/001
4. Employee now can fill the Expense, and can choose BILL/001 which will auto fill other information according to the bill.

I think this is not convenient. Why the vendor bill need to be created before employee can start filling the expense form and even before it is approved by manager ?

NEW: expense before invoice (auto)
1. Employee buy multiple service/items from and got the Tax Invoice from Vendor.
2. Employee can start filling Expense, and will key in items as in Tax Invoice (i.e., 3 items).
3. Select those item to create Expense Report as per normal (at this point invoice is not created yet).
4. Until when manager approved, the vendor bill will automatically created / open

This way, accountant don't need to interact the invoice, not before the expense is already approved by manager.

There will be other detailed points to consider. But I want to discuss on this key point first.

**As-Is : Create Invoice Before Expense** VS **New : Expense Auto Create Invoice**

Any opinion on this? Thank you!

**Comment by pedrobaeza** [comment]
This module was created for v8 and there were different flows there, and this has been ported as is during the rest of versions. The question is that there isn't the perfect flow, as invoice auto-creation doesn't fit also when invoices are sent to accounting department later through mail (as requested by the employee), and accountants book them without looking to the expenses, but want to reconcile them afterwards.

**Comment by kittiu** [comment]
@pedrobaeza thank you for clarifying. I will continue with hr_expense_invoice migration.

But I still think expense to create invoice still make some sense. 

Currently, Vendor Bill's sequence is used by both invoice and expense's journal entry, and thus make invoice document have number skipping.

May be expense should act like PO?
After expense approved by manager, then invoice document created (either to employee or to supplier), and then paid just like normal. This way, expense will have no account move. The sequence of invoice document will also in order.

In your mentioned case, when mailed in invoice is already executed by accountant without looking into hr expense, then I think invoice should be cancelled and start with expense to be correct. (also if the invoice is paid, it can't be reconciled with expense anyway too).

All in all, I know it is quite difficult to cover all cases, just want discuss to understand it better. Thanks.

**Comment by pedrobaeza** [comment]
You can add the facility to create the vendor bill on the fly.

**Comment by kittiu** [comment]
@pedrobaeza after playing around more. Since the invoice should not be create from Employee, or even use sudo() to create and validate it make not be good idea. I think the existing feature of hr_expense_invoice also make good sense to have accountant create it first.

Thank you for your opinion. I may close this issue for now until we found better way.
