### ISSUE TITLE
Payroll Computation --- Enhancement / New Feature V11

### ISSUE THREAD

**Issue by rjay1018** [OCA/hr#601]
Do we have this flexibility of computing the payroll base on the rules related to overtime and rest day policies? 

![overtime computation](https://user-images.githubusercontent.com/5526244/58303273-fa4ece80-7e21-11e9-96bd-470187c99f87.jpg)

Additional Information: Cola - Cost of Leaving Allowance

**Comment by pedrobaeza** [comment]
This issue tracker is for issues with current modules in this repository, which payroll is not, and any way, questions like this must be done in other place (forums, mailing lists).

**Comment by rjay1018** [comment]
Thanks
