### ISSUE TITLE
missing company filter in init_hook of adjust_employee_partners_pre

### ISSUE THREAD

**Issue by yucer** [OCA/hr#602]
**module**: hr_employee_data_from_work_address
**versions**: >= 8.0

**file**: init_hook.py
**method**: adjust_employee_partners_pre

This [sql query](https://github.com/OCA/hr/blob/646b39dadbc306df3128c13ed6e43e367d1e9620/hr_employee_data_from_work_address/init_hook.py#L35) in the init hooks seems to be missing a filter for the company: 

```python
    # point all remaining employees without address_id to a company partner to
    # satisfy newly introduced non null constraint
    cr.execute('update hr_employee e set address_id=c.partner_id '
'from res_company c where e.address_id is null')
```

According to the description it is assigned to a company partner but, which company ? Is the code intended to use the company of the employee ?

**Comment by pedrobaeza** [comment]
You are not indicating the module nor the version. Please propose the PR if you have the solution clear.

**Comment by yucer** [comment]
I have update it. Is there an OCA template for Issues ?

**Comment by pedrobaeza** [comment]
No, just common sense

**Comment by yucer** [comment]
It did provide the link to the code. There stays the module.

Anyway, that is an interesting point. Some projects like [swagger-codegen](https://github.com/swagger-api/swagger-codegen/issues) provides you a template when you click on "New Issue".

Maybe OCA repos can have some of these.

**Comment by yucer** [comment]
Note that I am not sure this is an error, this is some kind of informative Issue.
The behavior of the query may be intended.
