### ISSUE TITLE
Leaves Auto Approval only working with Leaves Manager group

### ISSUE THREAD

**Issue by neilmitchell-goodson** [OCA/hr#610]
module: hr_holidays_leave_auto_approve
version: 12.0

**Steps to reproduce**
- Configure a Leave Type as auto-approve. Create a leave request with that leave type from a user who does not belong to the _Leaves>Manager_ group.

**Current behavior**
The leave request is not automatically approved. Auto approval only seems to work when the requesting user belongs to the _Leaves>Manager_ group.
**Expected behavior**
Leave request is automatically approved by users not belonging to _Leaves>Manager_.
![Odoo 12 Leaves Auto Approve](https://user-images.githubusercontent.com/33225684/58542109-dc53e600-81f4-11e9-85b7-ce250ad6e32c.gif)

**Comment by vmelnych** [comment]
Same here, for the ordinary users the leave request does not get automatically approved.

**Comment by alexey-pelykh** [comment]
I'd start looking from https://github.com/OCA/hr/blob/572ec5fe76bee967fc8f8de638ccc522f02d5c46/hr_holidays_leave_auto_approve/models/hr_leave.py#L24

**Comment by vmelnych** [comment]
> I'd start looking from
> 
> https://github.com/OCA/hr/blob/572ec5fe76bee967fc8f8de638ccc522f02d5c46/hr_holidays_leave_auto_approve/models/hr_leave.py#L24

Thank you, Alexey! 
I will solve it by disabling this line, but this could be a good case for having a separate configuration parameter (for example, sick leaves do not have to be approved by anyone - they are just registered automatically).

**Comment by alexey-pelykh** [comment]
OCA would welcome a PR that enhances the module

**Comment by vmelnych** [comment]
Would you, please, elaborate what does PR mean here? Public Relations, Project Responsible, Product Responsible or anything else?
I would gladly carry out product coordination.

**Comment by alexey-pelykh** [comment]
@vmelnych just a pull request :)

**Comment by vmelnych** [comment]
Being a beginner in Python/Odoo sucks... Wasted a day, can't figure out why it does not work.
None of the requests with leave types marked as "Auto Validate" get approved automatically - requests still wait in the queue for a manager's approval.
I did many different ways by modifying or commenting lines, reinstalling all from scratch - to no avail.

**Comment by neilmitchell-goodson** [comment]
You're less of a noob than I; Kudos for trying!

**Comment by jarroyomorales** [comment]
The README on `hr_holidays_leave_auto_approve` says: Get sure that the administrative user belongs at least to the group Leaves/Officer.
The idea behind this module was probably that it is not necessary that HR employees validate leave requests they created. I dont think the idea of the module was to create a leave type that can be validated by everyone, if we want this behaviour we should create another module or try to modify this one.

**Comment by vmelnych** [comment]
I tested it on a standard demo database (v12), where admin user (Mitchell Admin) has the manager rights and demo user (Marc Demo) is subordinated to Mitchell and registers the sick leave. Ideally, the sick leave is automatically processed by the backend, while the manager is only informed about it.

**Comment by alexey-pelykh** [comment]
@jarroyomorales I suppose usecase of module that aids self-approve if I can do that being HR Officer is not that valuable, while auto-approve by "Odoo Bot" in case leave is configured so for sick leaves is quite a use-case. Though not for all business processes.

**Comment by jarroyomorales** [comment]
@alexey-pelykh Well, we are talking about two different things, this module just allows the HR officers to skip approving leaves created by them, which is not an amazing feature haha but it doesnt do any harm, I would actually enable this option in all the leave types. If a normal user asks for a leave, the process doesnt change but if a HR employee does it, the leave is auto approved.
The other thing is having a leave type that is autoapproved by everyone, maybe we can add this feature to the module.

**Comment by vmelnych** [comment]
@jarroyomorales, Alexey got me right - ideally, the leave is not being "auto-approved BY everyone", but by the Odoo Bot "FOR everyone". Thanks for having thought of this!

**Comment by jarroyomorales** [comment]
@vmelnych Oh, now I got you! I'm about to create a PR proposing something, tell me what you think.

**Comment by vmelnych** [comment]
Wow, gents, you've made my day!!! Thanks a lot!

**Comment by Rakibhossen-cell** [comment]
I love your  (https://computersciencehelf.blogspot.com/). I love your post. It very helpful post. Thanks

**Comment by vmelnych** [comment]
From what I see, release 13 has incorporated the feature under the Time Off option "Validation : No Validation".
