### ISSUE TITLE
[12.0] hr_expense_invoice: Inherit expense field's values

### ISSUE THREAD

**Issue by gustavovalverde** [OCA/hr#615]
When creating an invoice from an expense; all inheritable values should be passed to the invoice, like:
- Product
- Unit Price
- Quantity
- Taxes
- Bill Reference
- Date
- Account

**Comment by kittiu** [comment]
@gustavovalverde my understand of workflow when using it is module is,
- Employee doing expense will have to hand in paper tax invoice he/she got from vendor to accounting department first.
- Accountant will then create the tax invoice in Odoo and give reference number back to employee.
- Employee will then create expense and select the already created invoice number.

I also don't like the way it works, but it seem to be the workflow of this feature. What is yours?
Note: I am not the creator of this module, just my understanding.

**Comment by gustavovalverde** [comment]
@kittiu that workflow seems odd as the expense module was created for employees to register the expenses while out of the office, and the workflow is meant to be:

1. The employee register all his expenses with the basic information.
2. His manager selects the expenses that will be approved.
3. All paper tax invoice the employee got from vendor are handed to the accounting department (just the ones that got approved).
4. The Accountant will create an invoice for each expense (or maybe just one for all of them) with all the remaining information.

If the accountant has to retype all the information again, there's no sense on integrating the expense and invoicing apps.

**Comment by kittiu** [comment]
@gustavovalverde I understand your concern.
I used to discuss about this here https://github.com/OCA/hr/issues/585, as in V8, I used to create a module that will auto create invoice after confirm expense, then go on with normal invoice/payment process (not exact as you explain, but you got the idea). It is ok, but I can't deny that it is quite a lot of code to do at that time.

In v12, it is also different, account_expense_invoice, 1 invoice per expense, and multiple expense item will build up an expense report. Manager will approve on the expense report, after approve there is no way to go back to expense item to have accountant create invoice from it again (also it is many expense item to 1 invoice issue).

And this is the quote from @pedrobaeza 
> This module was created for v8 and there were different flows there, and this has been ported as is during the rest of versions. The question is that there isn't the perfect flow, as invoice auto-creation doesn't fit also when invoices are sent to accounting department later through mail (as requested by the employee), and accountants book them without looking to the expenses, but want to reconcile them afterwards.

So, I think, this module now isn't perfect. In our case, we explain the process will be, and they are OK. So, I guess it is usable.

**Comment by gustavovalverde** [comment]
I think that the easiest solution is to keep everything as-is (in the meanwhile); and just inheriting those fields when hitting the create and edit button, if there's not an existing invoice which can be selected. This would save all the re-type time to the accountant; and it won't change the actual workflow.

**Comment by kittiu** [comment]
You mean, when the Expense (hr.expense) is still in draft state, and before the manager approved, right?

**Comment by gustavovalverde** [comment]
In the meanwhile, yes.

**Comment by kittiu** [comment]
I am ok, @pedrobaeza any final comment?

**Comment by kittiu** [comment]
Hi I think it is a non-breaking feature. I already do the PR https://github.com/OCA/hr/pull/618

**Comment by pedrobaeza** [comment]
Reviewing v12, for me a flow can be:

* An employee submit its expense to the manager via a sheet.
* The manager approves the sheet.
* But before posting journal entries, an accountant / invoicing user can link an invoice to each line.
* If the amount of the invoice is equal to the expense amount, no problem.
* If any difference, then the user can refuse the expense and put a not about the problem, and repeat cycle.
* If not, when posting, the module will replace the journal entries according the invoice.

**Comment by kittiu** [comment]
@pedrobaeza accounting to yours,
> But before posting journal entries, an accountant / invoicing user can link an invoice to each line.

I think what is currently lacking hr_expense_invoice are,
1) Ability for accountant to link/create invoice after expense sheet already approved.
  - This can fix by adding invoice_id column as editable in Expense Sheet's Lines
  - With multiple expense lines, given each line is creating/edit a new invoice, I think it is still possible to pass each expense info to be invoice info as in PR #618

2) But if all expense lines will want to link to only 1 new invoice, may be we need new invoice_id field in Expense sheet? So that, if invoice is create/edit at Expense Sheet level, it can write down to all expense lines...

**Comment by gustavovalverde** [comment]
I do agree with @pedrobaeza workflow.  PR #618 is a step forward for this; I already approved it.

The only thing that I would **add** (in another PR) is an option to create a single invoice from the Expense Sheet with all the expense lines that did not had an invoice related to it.

**Comment by pedrobaeza** [comment]
Each expense might have a different invoice, so there should be a wizard for selecting lines without invoice for saying which ones you create the invoice for.

**Comment by kittiu** [comment]
I will open new PR

**Comment by kittiu** [comment]
Finished the PR https://github.com/OCA/hr/pull/622 as discussed.
@pedrobaeza when we change the content in folder readme, will the README.rst gets update automatically by ocabot? Or do we need to delete it first?
