### ISSUE TITLE
[IMP] hr_attendance_rfid: Reader card code

### ISSUE THREAD

**Issue by fuentes73** [OCA/hr#619]
Hi, I've been testing `hr_attendance_rfid` module with Eficent RAS project and I noticed that:
 * Reading a card with RAS (or any device that uses this [library](https://github.com/mxgxw/MFRC522-python)) the result i's a hex code like `51e69621`
* Reading the same card with a usb reader (at least with ours) the result is a number like `0563537489`

If you have registered the `rfid_card_code` of each employee with the usb reader, now you have a problem. 
As it can be converted `0563537489` into `51e69621` and vice versa, Which solution do you think is better?

1.  
    - Create a new field `rfid_card_hex_code` and compute it from `rfid_card_code`. If `rfid_card_code` is already a hex code do nothing, just copy the value.
    - Check at `register_attendance` function if `card_code` is equal to `rfid_card_code` or `rfid_card_hex_code`

2. Modify `register_attendance` function in order to compute decimal and hexadecimal value of `card_code` and check if any is equal to `rfid_card_code`

I'll open a PR with the chosen solution.

cc @omar7r @hveficent @jbeficent

**Comment by HviorForgeFlow** [comment]
USB Reader normally have more than one codification allowed. I don't know which USB Reader you have, but on my case I could change codification to 8H REVERSE to fit with hexadecimal readers.

**Comment by fuentes73** [comment]
Didn't remember of this issue.
 @hveficent Thank's for the info.
