### ISSUE TITLE
[IMP] [hr_employee_calendar_planning ] If the calendar does not have dates the hook renames it to ' ... False-False'

### ISSUE THREAD

**Issue by meigallodixital** [OCA/hr#620]
https://github.com/OCA/hr/blob/2ca9293c5a14b1103df171f43c41ef36137225ee/hr_employee_calendar_planning/hooks.py#L33

It should have a neutral name, such as 'Default Working Time' for example ...

**Comment by jarroyomorales** [comment]
The calendar generated is invisible anyways but we can do PR if you need it to have a name to use it somewhere else.
