### ISSUE TITLE
[12.0] Travis failing

### ISSUE THREAD

**Issue by jarroyomorales** [OCA/hr#629]
I don't know if there has been a recent odoo change but some tests are failing. They were working fine for me until I updated odoo.

The error is always the same, requesting holidays before the `validity_start` field and the solution is simple, setting it to false on the tests.
For now I have detected it in 'hr_holidays_accrual_advanced` and `hr_holidays_leave_repeated` but it may happen in other modules.

I'm already solving it but I don't know if it is the best solution, thank you!

**Comment by pedrobaeza** [comment]
Don't open issue if you are going to open a PR afterwards.
