### ISSUE TITLE
[11.0] hr_holidays_compute days, fields are True by default

### ISSUE THREAD

**Issue by jarroyomorales** [OCA/hr#653]
The new field `compute_full_days` in this module is set as True by default, which can (and I think it is) cause problems to other modules tests since they shouldn't take in account that the computation of days has been changed by this module.

https://github.com/OCA/hr/blob/11.0/hr_holidays_compute_days/models/hr_holidays_status.py#L19

**Comment by jarroyomorales** [comment]
@pedrobaeza What do you think of this? Should I create a PR?

**Comment by jarroyomorales** [comment]
And I think it is the same case with the other field, exclude_rest_days`. 
A field that changes the result of the number of days computation shouldn't be default True because other modules can't do anything against it

**Comment by pedrobaeza** [comment]
Well, it shouldn't be too much problem, as you normally do that for the leaves. Any way, you can add code for inhibiting that behavior on the module itself detecting if you are in test mode and not testing the module itself.

**Comment by jarroyomorales** [comment]
The module itself works fine, the problem is just with the tests. You can always ask if the leave type has the field `compute_full_days` and set it to False but I dont know if thats the best solution since these two modules are independent.

**Comment by pedrobaeza** [comment]
As said, you can inhibit the behavior when testing other modules:

1. Add `from odoo.tools import config`.
2. On the code that changes the behavior if `compute_full_days`, check if `config['test_enable']` and there's not a specific context key. Then ignore behavior.
3. On `hr_holidays_compute_days` module tests, add that context.

Example of this: https://github.com/OCA/bank-payment/blob/8.0/account_payment_transfer_reconcile_batch/models/payment_order.py#L28

**Comment by jarroyomorales** [comment]
Solved! At least in 11.0, should we also apply this to 12.0? @pedrobaeza

**Comment by pedrobaeza** [comment]
Yes, please propose PR

**Comment by jarroyomorales** [comment]
The PR of the migration https://github.com/OCA/hr/pull/603 was closed since this module is already included in odoo 12.0 core so I think we can close this issue.
