### ISSUE TITLE
display multiple contract of each employee

### ISSUE THREAD

**Issue by slom44** [OCA/hr#664]
Hi guys,

first of all I'm not sure if I'm doing this correct or not, but I hope that I can ask in here and you can help me with the answers

let us say that I have 10 employees
7 of them has multiple contracts
2 of them has only one contract
1 of them has no contract

when I fetch all the employees I can only see 10 rows, each employee in single row

but what I need is to list all the employees AND the contracts
so I should have it like this
John -- contract 1 --- other information
John -- contract 2 --- other information
Ross -- contract 1 --- other information
Rami -- no contracts --- other information

I hope that I explained my question properly
thanks in advance

**Comment by jarroyomorales** [comment]
This isnt implemented yet. If you fetch all employees you see 10 of course and if you fetch contracts you will see a list of the 16 contracts but you will not see that Rami doesnt have a one.
The best solution for your specific problem would be to create a report that iterates through employees and prints their active(didnt expire) contracts or 'no contract' if the employee doesnt have one currently.
