### ISSUE TITLE
hr_holidays_public not shown in Calendar

### ISSUE THREAD

**Issue by nikul-serpentcs** [OCA/hr#699]
I configure Public Holidays but not shown in the Calendar menu.

Is there any functionality to Show Holidays in the Calendar view?

Ex. I created 1 Public Holidays (01/01/2020 -> New Year Celebration) records, but not shown in Calendar view than some time Team Leader(Or Head) arranged client meeting on public holiday. then two dates conflict.

So, how can we avoid this kind of scenario? 

@pedrobaeza @mtelahun @feketemihai

**Comment by pedrobaeza** [comment]
See #649
