### ISSUE TITLE
[BUG][12.0][hr_expense_invoice] Duplicated expenses

### ISSUE THREAD

**Issue by rafaelbn** [OCA/hr#708]
Hello @kittiu @tbaden @gustavovalverde @luistorresm @ps-tubtim ,

This module is incorrect from the Account point of view as it duplicated the expenses, I mean:

- The expense go to a "expense account"
- The invoice go to a "expense account"

If the hr_expense has an invoice related then the account move line shouldn't be duplicated!

![2019-10-21_0-09-05](https://user-images.githubusercontent.com/8736623/67167202-5bf67300-f397-11e9-8494-7ae588890e9c.png)

cc @pedrobaeza @carlosdauden @tecnativa

**Comment by luistorresm** [comment]
Hello @rafaelbn 

Could you send a video where you show the error, please?

You can use [the OCA runbot](https://runbot.odoo-community.org/runbot/repo/github-com-oca-hr-116)

Regards

**Comment by kittiu** [comment]
Hi, I am testing, but it seem ok. May be about your configuration? Here is what I have,

- EX's journal entry
![image](https://user-images.githubusercontent.com/1973598/67542249-3dd19f80-f716-11e9-915f-ffa465cbe90c.png)

- INV's journal entry
![image](https://user-images.githubusercontent.com/1973598/67542260-475b0780-f716-11e9-88e5-41150de0c1ee.png)

When invoice is confirmed, it will be in status Paid immediately (auto reconcile with expense's journal entry). Then, I click register payment in Expense. Here is the final reconciled item. Seem ok though.

![image](https://user-images.githubusercontent.com/1973598/67542349-9f920980-f716-11e9-943f-05fe29fd9101.png)

**Comment by rafaelbn** [comment]
Dear @luistorresm @kittiu ,

Thanks for your answers. It's true, I tested in runbot and works like a charm! But not in our self production instance... I will review then internally.

cc @pedrobaeza
