### ISSUE TITLE
[11.0|12.0] Compatible Hardware RFID Reader

### ISSUE THREAD

**Issue by harlibeub** [OCA/hr#715]
module: hr_attendance_rfid
version: 11.0, 12.0,...

**Steps to reproduce**
searching for compatible hardware to read rfid cards.

**Current behavior**
in module desc. you mention to existing hardware, which should be able to config. to call needed odoo url to register empl. attendances... but you don't list any hardware examples or recommended hardware which are network driven... or even usb

**Expected behavior**
please give us some recomm. list of hardware to choose... would be very nice

t.y.

**Comment by HviorForgeFlow** [comment]
@harlibeub 
At Eficent, we've developed a hardware solution.
Visit  https://www.eficent.com/product for more information

**Comment by pedrobaeza** [comment]
Yeah, and nothing to do with the Odoo module itself, that only provides a helper for storing the RFID number and a method for preparing the attendance, so closing.
