### ISSUE TITLE
[12.0] hr_expense_invoice,hr_expense_advance_clearing: Register Payment appear

### ISSUE THREAD

**Issue by abdallamhafeez** [OCA/hr#716]
Hello,
I  have case with module `hr_expense_advance_clearing` and `hr_expense_invoice` that if expense is linked to vendor bill and with advance expense, there is button "Register Payment" appear and allow to add payment

**Comment by kittiu** [comment]
Hi we are aware of that. These 2 module are for different use case and not yet tested together.
But will be soon, as our time allowed.
