### ISSUE TITLE
Public holidays not showing in calendar and not exclude from leave

### ISSUE THREAD

**Issue by supakornkim** [OCA/hr#727]
V12 

1. Public holidays not showing in calendar 
2. Leave not exclude public holiday
3. Leave show incorrect in calendar ( leave 3 days but highlight 4 days )
![image](https://user-images.githubusercontent.com/19331506/68986485-60a52e80-0852-11ea-8b19-0a894f0d5c74.png)

**Comment by pedrobaeza** [comment]
1. Not implemented.
2. You need to configuration the leave type.
3. It's due to timezones.

Next time, please only one problem per issue, and give full details.
