### ISSUE TITLE
[RFC] Move hr_attendance_* modules in new OCA/hr-attendance repository

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/hr#732]
The title says it all :)

I think we have too much modules here and we can specialize those that takes the attendance area in that repo.

**Comment by LoisRForgeFlow** [comment]
+1

**Comment by LoisRForgeFlow** [comment]
maybe starting in 13.0?

**Comment by pedrobaeza** [comment]
Yeah, that should be something for 13.0 I guess, as now moving this in 12.0 can be confusing for already deployed instances, unless you think it's better to have everything in one place directly.

**Comment by jarroyomorales** [comment]
+1 to start at 13.0. But then should we do the same for `hr_holidays_*` modules?

**Comment by pedrobaeza** [comment]
Yes, it makes sense as well.

**Comment by jarroyomorales** [comment]
Some modules are already getting merged to 13.0, it think we should make a decision on this before more modules are migrated here. @OCA/human-resources-maintainers

**Comment by pedrobaeza** [comment]
@OCA/board what do you think about this?

**Comment by alexey-pelykh** [comment]
I'd agree, yet applying same criteria we can move hr_expense_* to new repo as well

**Comment by JayVora-SerpentCS** [comment]
In my opinion, HR is a big idea. Should definitely put all in one repo.

**Comment by pedrobaeza** [comment]
I count 3 in favor vs 1 against. Can we consider this enough quorum for doing it?

**Comment by pedrobaeza** [comment]
@astirpe what do you think about this?

**Comment by astirpe** [comment]
For me it's okay to the three new repos starting from V13.
I'm wondering why @JayVora-SerpentCS and others prefer to keep one single repo. Is there a valid reason for it? Maybe I could change idea if I read some valid motivation.

**Comment by JayVora-SerpentCS** [comment]
My simple belief is, should move only when there are 10+ modules with each sector.
Otherwise dependencies will be hard.
In any case, developers find a way to get used to OCA decision.

**Comment by pedrobaeza** [comment]
@JayVora-SerpentCS and do you think it's better to have 41 modules in one repo? Any way, there are already 5 modules for hr_attendance_*, another 5 for hr_expense_*, 10 for hr_holidays_*, and more coming from our sides, so I think they are enough for being separate. And Odoo has also split menus since a lot for these areas.

**Comment by JayVora-SerpentCS** [comment]
We can split then! numbers justify, thanks.

**Comment by feketemihai** [comment]
I would split it also, because it will simplify the structure and also people who want only one repo, it will not get another 35-40 modules loaded.

**Comment by pedrobaeza** [comment]
Repositories created and the only existing module has been moved. Thanks to all.
