### ISSUE TITLE
Public Holidays not exluded from leaves calculation (tested on official runbot)

### ISSUE THREAD

**Issue by tableconnect** [OCA/hr#769]
Hello,

I was just testing the plugin on the proposed runbot-link which should be 11.0.
(used Employee: Peter Parker)

I´ve created public holidays several times and taken care to check "exclude public holidays" with the selected leave-type.
I´ve also made sure to change the public holidays country to the same country of the employee but that also did not help. 

This has been reported before in december but received not solution/satisfactory answer.
Hopefully somebody can help us out here, because after all that is the main purpose of this plugin...

Thanks, Johann

Sidenote: whenever I set the Public Holiday Year to 2020 it is then displayed as "2,020"

**Comment by jarroyomorales** [comment]
@tableconnect I have just tested `hr_holidays_public` in a local database and it works as expected. I suspect the issue might be in `hr_holidays_hour`.
The format how integers are displayed depends on the language the user is using. If you change the language to Spanish, for example, it will be displayed as "2.020".

**Comment by gradox2020** [comment]
@jarroyomorales I have the same problem in Odoo 12

**Comment by thopy** [comment]
I had the same problem with Odoo 11 but after removing the value in state_ids on the record of hr.holidays.public.line it worked as expected.
