### ISSUE TITLE
[12.0] hr_attendance_geolocation: Can't Check In/Check Out on mobile phone

### ISSUE THREAD

**Issue by ps-tubtim** [OCA/hr#776]
I have case with module `hr_attendance_geolocation`.

Case:
1. Install `hr_attendance` without `hr_attendance_geolocation`: I can Check in/Check out on mobile phone.
2. Install `hr_attendance` and `hr_attendance_geolocation`: I can't Check in/Check out on mobile phone.

Note: I test in app chrome, safari.

**Comment by kittiu** [comment]
Another question: This module is intended for GPS location or IP address location?

**Comment by cvinh** [comment]
@ps-tubtim do you have any error message ?
Are you using the kiosk mode with pin code ?

**Comment by ps-tubtim** [comment]
@cvinh 

> do you have any error message ?

Normal mode and kiosk mode don't show error messages.

> Are you using the kiosk mode with pin code ?

No, I'm using the kiosk mode with a select employee.

**Normal**
![Peek 2020-06-04 13-47](https://user-images.githubusercontent.com/51266019/83724540-a7316d80-a66a-11ea-904e-53de1d0f2788.gif)

**Kiosk**
![Peek 2020-06-04 13-49](https://user-images.githubusercontent.com/51266019/83724566-b44e5c80-a66a-11ea-82f4-6996f7370ba1.gif)

![Selection_117](https://user-images.githubusercontent.com/51266019/83724599-c16b4b80-a66a-11ea-8c1b-74412f29a761.png)

**Comment by cvinh** [comment]
@ps-tubtim I'm sorry I cannot reproduce your issue (BTW I don't have any iphone)
Can you test with an android phone ?
@AdriaGForgeFlow

**Comment by cvinh** [comment]
@kittiu It uses gps with smartphone if the user allows it
With a computer that does not have gps localization it uses IP Address

**Comment by Saran440** [comment]
@cvinh I tested on android phone (version 9) and can't check in too.
![error](https://user-images.githubusercontent.com/20896369/83935768-e2f14200-a7e6-11ea-9e60-c8b72a889811.gif)

but if i installed attendance module only. i can check in
![normal](https://user-images.githubusercontent.com/20896369/83935775-fa302f80-a7e6-11ea-82f0-33ea34ae6c2b.gif)

**Comment by cvinh** [comment]
I'm sorry to hear that because I really don't know what can the problem be...
Did you use google chrome ?
Are you on the 12.0 branch ?
Are you using the lastest odoo commit ?
With a computer do you manage to checkin ?
Can you debug with a browser console ?
We do not face the problem here...

**Comment by Saran440** [comment]
@cvinh 
Did you use google chrome ? -> yes, I use google chrome.
Are you on the 12.0 branch ? -> sure
Are you using the lastest odoo commit ? -> yes, I pull odoo and hr (oca) today.
With a computer do you manage to checkin ? -> it works on my computer. but not work on mobile.
Can you debug with a browser console ? -> I don't know how to debug on mobile. Can you advise me?

**Comment by lgit-it** [comment]
my 2 cents (as I have the same problem)
it seems that if you disable geoloc in the browser for the site (or geolocation is disabled on the phone) the javascript has no fall-back, 
and it is very hard to find where the browser store that config information.

I think it's fixable on the js part but unfortunately i'm unable...
