### ISSUE TITLE
[12.0] hr_expense_advance_clearing 

### ISSUE THREAD

**Issue by supakornkim** [OCA/hr#796]
Clear Advance
1. At the step number 2. Search for the Advance you want to clear, or use filter "Advance (not cleared)" to see all uncleared advance.
This step, I cannot see uncleared advance.

2. So, I go create Expense->create report -> and select clear advance, this can select the advance that I created before. But the advance remaining amount is 0.00.

![image](https://user-images.githubusercontent.com/19331506/75855118-1dcc8e00-5e24-11ea-859d-f59ea8a04fd7.png)

I continue the process until paid status.
Then, I cannot find the button to return the Advance. (Advance 500, expense 30, need to return 470)

3. So, I try to add more expense to use the rest of advance money (470)
I go to create expense-> create report ->select clear advance. but this time cannot see my advance.

![image](https://user-images.githubusercontent.com/19331506/75855888-c8917c00-5e25-11ea-890d-dbd7e5339a5e.png)

**Comment by Saran440** [comment]
2. In Employee Advance, you need process until state = Paid.
3. You cannot see because you clear advance from 2.

**Comment by supakornkim** [comment]
2. Yes, the status of Employee Advance is already paid
3. I will try again.

**Comment by Saran440** [comment]
My step:
1. Create Advance and normal process
![Selection_007](https://user-images.githubusercontent.com/20896369/75862530-b0275e80-5e31-11ea-8224-17cae3b2e423.png)
2. Create normal expense and select Advance. It show advance remaining correct.
![Selection_008](https://user-images.githubusercontent.com/20896369/75862681-e533b100-5e31-11ea-8592-db70f4f83241.png)

**Comment by supakornkim** [comment]
1. Create Advance and normal process 
![image](https://user-images.githubusercontent.com/19331506/75942423-e8c44800-5ec4-11ea-86d0-8d705ed35a5c.png)

2. Create Expense clear advance.. amount = 0.
![image](https://user-images.githubusercontent.com/19331506/75942529-2d4fe380-5ec5-11ea-8821-3a2de1a458c9.png)

What have I missed...

**Comment by supakornkim** [comment]
ok. when coming to status Approved the amount coming up
![image](https://user-images.githubusercontent.com/19331506/75942682-a9e2c200-5ec5-11ea-89ea-2df8e0be6a95.png)

then, I change user to accounting and posting
![image](https://user-images.githubusercontent.com/19331506/75942747-d0a0f880-5ec5-11ea-803c-e985fba8caa3.png)

No button to return Advance

**Comment by Saran440** [comment]
@supakornkim 
- filter `Advance (not cleared)` you can see at menu My Expense Reports
- Button Clear Advance and Return Advance is at Employee Advance only

**Comment by hitrosol** [comment]
Hi @Saran440, i tried this module in the my local and runbot. It's working well until I install the hr_expense_payment_difference.
![image](https://user-images.githubusercontent.com/5949936/101968334-43a77e80-3c51-11eb-8980-a288b10710a4.png)


The amount to clear become zero after Register Payment. No further clear advance button.

**Comment by Saran440** [comment]
@hitrosol Hi, thank you for your feedback and Sorry for reply late. Could you open new issue and explain step to error from here https://github.com/OCA/hr/issues/new?
