### ISSUE TITLE
[12.0] hr_attendance_modification_tracking  easy view time changed attendances

### ISSUE THREAD

**Issue by js-landoo** [OCA/hr#836]
I propose to add this feature:
Easily view wich attendances have manual time changes.

Use case: The HR manager needs to be able to see in a fast and clear way which of the attendance have had manual changes of any date-time field. Clicking in each record is not useful for someone who reviews and approves each month about 40 attendances per person.

Proposed solution:
Add a computed field to the attendance that will be displayed in list and form views, showing that it has been manually changed.
It will be a boolean field "Manual time change" that will have a value of True in case of having any manual change in Check In or Check Out fields.
Filtering and grouping will be added for this field.

**Comment by jarroyomorales** [comment]
Very nice and useful! Can you propose a PR and we discuss it there?

**Comment by js-landoo** [comment]
PR#837 proposed
[https://github.com/OCA/hr/pull/837](url)
Thanks @jarroyomorales
