### ISSUE TITLE
[10.0-12.0] hr_attendance_report_theoretical_time

### ISSUE THREAD

**Issue by busmanapps** [OCA/hr#838]
Hi.
We have detected a little issue that affects the editions 10, 11 and 12 with the module "hr_attendance_report_theoretical_time".

[https://github.com/OCA/hr/blob/10.0/hr_attendance_report_theoretical_time/reports/hr_attendance_theoretical_time_report_views.xml](url)

When trying to download the xls file of the pivot view "hr_attendance_theoretical_view_pivot", it throws an exception saying that the field "title" cannot be found in the object "jdata".

The issue comes from this line:
`<pivot disable_linking="1">`

It should be like this:
`<pivot string="Attendances" disable_linking="1">`
(In older versions, it was like that and it worked fine).

With this simple change it starts working, does not throw any exceptions and it allows to download the xls file.

We have been looking for that line in the different branches and it looks like it is in the branches 10, 11 and 12.

**Comment by pedrobaeza** [comment]
In English, please. Do the PR changing that.
