### ISSUE TITLE
Do we need to rewrite module to new api before moving it out from _unported?

### ISSUE THREAD

**Issue by tmotyl** [OCA/hr#84]
Some modules works in v8 as they are (e.g. hr_public_holidays).
Do we need to rewrite them to new api, or can we first move them out from unported and then port to new API?

**Comment by ghost** [comment]
Hi @tmotyl, hr_public_holidays has no unit test. Even if this module will work on v8, it will need to be reviewed. If we port it to v8 unchanged, nobody will take the time to improve it after.

**Comment by yvaucher** [comment]
In v9 old api compatibility must be dropped, so it must be done sooner or later.
v8 API is much more stable than on its release date, but still there can be some issue mostly when overwriting an old API object with new API.

So what is generally done, is that 7.0 modules ported to 8.0 will be accepted with old API.
But new modules should be in new API.

So if you can port a module and test it just by setting installable = True just do it.
