### ISSUE TITLE
[12.0]  hr_attendance_modification_tracking: Issue on las upgrade

### ISSUE THREAD

**Issue by etobella** [OCA/hr#857]
With the new computed field, it takes too long to upgrade / install if there is  existing records (a large set, obviously).

I think we need to create a `pre_init_hook` and a `pre-migration` script creating the column in order to avoid this issue.

@js-landoo @jarroyomorales @alexey-pelykh @Saran440 @marcelsavegnago

**Comment by jarroyomorales** [comment]
Yes, I also think we need a pre init for new instalations and a migration script for upgrades. Adding the new column will prevent the new stored computed field be calculated in old attendances, which is nice for a fast installation. This should be added to the readme so whoever wants to compute old attendances does it manually.

The other option is not doing anything but at least adding on the readme that in can take a long time for instances with a lot of attendances...

**Comment by Saran440** [comment]
Fixed https://github.com/OCA/hr/pull/858
