### ISSUE TITLE
[RFC] gamification_award_report

### ISSUE THREAD

**Issue by max3903** [OCA/hr#868]
# Description

This module adds a report on employee awards.

# Usage

* Go to Employees > Reporting > Awards

# Technical Specifications

## gamification.badge.user

- [ ] Add a pivot view with the following measure: Count.
- [ ] Add a menu item "Employees > Reporting > Awards" to open the pivot view

**Comment by pedrobaeza** [comment]
Shouldn't we create OCA/gamification?

**Comment by alexey-pelykh** [comment]
Would be proper thing to do

**Comment by dreispt** [comment]
Not sure if it's worth the trouble.
I would rather only split when there are already enough gamification modules justifying it.

**Comment by max3903** [comment]
Requirement was dropped.
