### ISSUE TITLE
Potential new module, auto create employee when creating a user

### ISSUE THREAD

**Issue by crobarcro** [OCA/hr#871]
Hi,

I'm trying to create a new app which automatically creates a new employee when creating a new user. In my case, this was because I have a connection to an LDAP directory of users and they are created as contacts, rather than employees in Odoo. I tried to create the app for Odoo 12, which you can find here:

https://github.com/crobarcro/odoo-employee-from-users

I'd be happy to clean this up and have it become a part of OCA, if it was of interest. The only problem is, it doesn't actually work yet! When I try to install the app I get an error about `employee_id` not found when processing a view. 

The app essentially boils down to this though:
```

from odoo import models, fields, api


class EmployeeUsers(models.Model):
    _inherit = 'res.users'

    employee_id = fields.Many2one('hr.employee',
                                  string='Related Employee', ondelete='restrict',
                                  help='Employee-related data of the user', auto_join=True)

    @api.model
    def create(self, vals):
        result = super(EmployeeUsers, self).create(vals)
        result['employee_id'] = self.env['hr.employee'].create({'name': result['name'],
                                                                'user_id': result['id'],
                                                                'address_home_id': result['partner_id'].id})
        return result
```

Is there any chance someone might have a quick look to see if there's an obvious problem for this very small app?

The app was originally forked from this:

https://apps.odoo.com/apps/modules/10.0/employee_creation_from_user/

which is LGPL v3.0

**Comment by jarroyomorales** [comment]
Hi @crobarcro !

I have just tested this module and it is working as expected! I didnt see any error.
Can you propose this with a PR to OCA/hr so people can discuss about it and give you comments about the code?

Thank you!

**Comment by pedrobaeza** [comment]
The problem is that the CLA is not signed by original authors, which is a requirement.

**Comment by dreispt** [comment]
@crobarcro An external directory will also have many non-employees, such as external users and system accounts.
How do you address these cases?

**Comment by crobarcro** [comment]
> The problem is that the CLA is not signed by original authors, which is a requirement.

@pedrobaeza  Good point, this could be a problem, perhaps I could get the original authors to release it as they seem to have abandoned the app since Odoo 10.

> @crobarcro An external directory will also have many non-employees, such as external users and system accounts.
> How do you address these cases?

@dreispt I don't ... yet. This is a work in progress

In principle I would like to do this based on some LDAP attribute value, perhaps configurable by the user, or perhaps by LDAP groups. 

> Hi @crobarcro !
> 
> I have just tested this module and it is working as expected! I didnt see any error.
> Can you propose this with a PR to OCA/hr so people can discuss about it and give you comments about the code?
> 
> Thank you!

@jarroyomorales Thanks for testing! I wonder why I am getting the installation error then. Perhaps I'm not doing the correct installation procedure.

**Comment by Saran440** [comment]
> @crobarcro An external directory will also have many non-employees, such as external users and system accounts.
> How do you address these cases?

@crobarcro @dreispt 
I think we should create new button or checkbox`create employee` on users view.
What do you think?

**Comment by dreispt** [comment]
> I think we should create new button or checkboxcreate employee on users view.

Sounds good. Make it a button or and Action menu option.
The Action menu can even be made to work on the list view to mass create employees.
I suggest naming it " Convert to Employee".
It would also be nice to have a related field, or smart button, to identify if you have a related employee, and navigate to it.
