### ISSUE TITLE
[RFC] hr_expense_receipt_require

### ISSUE THREAD

**Issue by max3903** [OCA/hr#872]
This module allows you to define expense products that requires a receipt to be submitted.

# Configuration

* Go to Expenses > Configuration > Expense Products
* Create or select a product
* Check the box "Require a receipt"

# Usage

* Create an expense with the previous product
* Try to submit the expense without an attachment --> "You need to provide a receipt to submit this expense!"
* Upload a file as an attachment and re-submit

# Technical specifications

## product.template

* Add a boolean field "Require a receipt" (expense_receipt_required)
* Show the field on the expense product form view (Expenses > Configuration > Expense Products)

## hr.expense

* When the expense is submitted, check that there is a receipt if the product requires a receipt (expense_receipt_required). Raise a UserError if there is no attachment "You need to provide a receipt to submit this expense!"

**Comment by alexey-pelykh** [comment]
`hr_expense_receipt_require`
