### ISSUE TITLE
[RFC] hr_expense_analytic_require

### ISSUE THREAD

**Issue by max3903** [OCA/hr#873]
This module allows you to make the analytic account on an expense a required field.

# Configuration

* Go to Expenses > Configuration > Settings
* Activate the analytic accounting
* Set a default analytic account

# Usage

* Go to Expenses
* Create or open an expense. The analytic account is required.

# Technical specifications

## res.company

* Add a many2one field "Default Analytic Account for Expenses" (default_expense_analytic_id) to account.analytic.

## res.config.settings

* Display the setting group_analytic_accounting on the expense settings
* Add the setting to set the "Default Analytic Account for Expenses" on the company. The field is displayed only if the previous setting is selected.

## hr.expense

* Edit the field analytic_account_id to be required and default to default_expense_analytic_id from the company

**Comment by alexey-pelykh** [comment]
`hr_expense_analytic_require`

**Comment by rvalyi** [comment]
Hello, isn't this covered by our https://github.com/OCA/account-analytic/tree/12.0/account_analytic_required module already?
An expense will typically envolve an `account.user_type_id` for which you can set the property_analytic_policy to required, or do I miss something?

**Comment by max3903** [comment]
@rvalyi You are right. That would fulfill the required field part. I just added an option to have a default AA in case the expense is created from an email (or a receipt upload).

**Comment by max3903** [comment]
@rvalyi Second thought. The policy applies to all the accounts of the same type... That's too broad for my requirement. I can have journal item on expense-type accounts without AA. I just need a AA on accounts used by expensed product.
