### ISSUE TITLE
hr_expense_portal

### ISSUE THREAD

**Issue by max3903** [OCA/hr#886]
This module allows your customers to access the expenses related to their projects including the receipts.

# Usage

* Go to Expenses
* Create an expense
* Select a sale order and attach the receipt
* Submit, approve and post the journal entries

* As the customer of the sale order, go to the portal My Account > Expenses
* Open the expense and download the receipt

# Technical Specifications

Dependencies: sale_expense

## hr.expense

* Add a many2one field related to the customer of the sale order

## Security

* Add the record rule for the customer to read his own expense only

## Website

* Add the controller to browse approved expenses
* Add the option "Expenses" to the portal menu
* Add the list view and form views including the links to download the receipt. See example with https://apps.odoo.com/apps/modules/12.0/expense_customer_portal/

**Comment by nimarosa** [comment]
Closed till it was merged long time ago.
