### ISSUE TITLE
V12: Bug when combining the hr_expense_advance_clearing with hr_expense_payment_difference.

### ISSUE THREAD

**Issue by hitrosol** [OCA/hr#955]
Hi @Saran440, sorry for late response. I try to reproduce the steps as follow:
1. Install hr_expense_advance_clearing
2. Install hr_expense_payment_difference
3. Create new Cash Advance Request Report
4. Submit
5. Approve
6. Post
![image](https://user-images.githubusercontent.com/5949936/103540098-bfe95680-4ecb-11eb-9882-beafd7c85870.png)

7. Register Payment. 
![image](https://user-images.githubusercontent.com/5949936/103540121-cd9edc00-4ecb-11eb-8bc0-963010ec1ba3.png)

8. After Register Payment, the Amount to clear becomes zero. 
![image](https://user-images.githubusercontent.com/5949936/103540144-d7284400-4ecb-11eb-8817-b83dd6f7b02b.png)

9. The Clear Advance & Return Advance are not appear in this stage as well.
9. The result, the cash advance can't be cleared.

The hr_expense_advance_clearing is working good if i don't install the hr_expense_payment_difference
![image](https://user-images.githubusercontent.com/5949936/103540209-f8893000-4ecb-11eb-98ce-50a0049549d1.png)
The Amount to clear and the Clear Advance & Return Advance buttons are there.

Hopefully this is clear enough to give the current situation.

Thanks,

**Comment by Saran440** [comment]
@hitrosol Fixed. Please, Review and test this PR https://github.com/OCA/hr/pull/957
Thank you for your find bug on this module :)
