### ISSUE TITLE
[12.0] hr_expense_invoice : can not create invoice from expense.sheet anymore ?

### ISSUE THREAD

**Issue by njeudy** [OCA/hr#987]
Hello, for the last version of module some of code was removed and this is not possible anymore:

Create one invoice to multiple expenses

    Create an expense sheet with one or multiple expense lines
    After approved, click button "Create Vendor Bill"
    Select multiple expense to create an invoice, and process it.
    New invoice will be create and link to the selected expense lines.
    Validate newly create invoice.
    On paying expense sheet, you are reconciling supplier invoice(s) too.

We use this on a customer prod database and it crash in update test mode. Is this not available ? why to remove this ?
how can I create an invoice from expense.sheet now ?

the commit where this was removed:

https://github.com/OCA/hr/commit/30e2a40bc058986e3639473543116bc1b3485b90#diff-bc2f79796c7bfccdaf4fbe61d228c0022f46b8c1f827ec6f7f9b6de6e9dfbfec

@pedrobaeza what is the good way now ?

**Comment by pedrobaeza** [comment]
Creating an invoice for a whole sheet is totally incorrect. You can create an invoice per line, and now you have the wizard at line level.

**Comment by njeudy** [comment]
I'm Sorry but that's not a way to do this. Removing a model for a minor update Can crash production database. Should deprecate this and remove this in major update .. or just Mask Button to not crash database like this !! Fasttrack a commit that remove a model from database is dangerous and not fair...

I use this assistant to create all single invoice per Line ... One click for all...

**Comment by pedrobaeza** [comment]
This is not breaking any database. What is not correct are the journal items generated if you post a sheet with the same invoice for several lines, and that's why the wizard should be removed immediately.

**Comment by njeudy** [comment]
I inherit 'hr.expense.create.invoice' for my customer to optimize invoice creation in there flow .. so it break the database because of removing this models from 12.0.3.4 to 12.0.4.0 without any review. Please don't break model in minor review. Your right, this assistant can do account.move problem, but not in all cases and your not the only one person to use oca module.

I will change my code to add this assistant, that not a problem. 

to complet, i didn't find any assitant at the line level ? can you explain me the new way to create invoice from line, à just see a many2one field with default value in context, that can not be change by account manager after approved stage .. Don't understand how to use it ..

**Comment by pedrobaeza** [comment]
Maybe such wizard is not backported to v12. @victoralmau can you confirm if the wizard by line is in v12?

**Comment by pedrobaeza** [comment]
For completing info, it was queried to the original contributor of such feature in https://github.com/OCA/hr-expense/pull/32#discussion_r602349092, so it was not a lonely decision.

**Comment by njeudy** [comment]
I see this request, but was fast track, just technativa review and Merge as minor with removing modèles. That is not the oca rules, and Can cause lesser quality.

I will backport assistant because actually, this module is broken in v12

**Comment by pedrobaeza** [comment]
Please don't insist. The module is not broken. You are able to create the invoice for one line (from the many2one), that is the correct case. It's OK that you backport the wizard, or we can do it next week.

About what you call the fast-track, it was not fast, as 5 days passed, and it was done by a PSC, so they are still OCA rules, and the result would be the same waiting more. Or are you telling me that you was going to review the PR, what you don't usually do with the rest of the OCA?
