### ISSUE TITLE
[12] hr_attendance_report_theoretical_time: days with leave and without attendance appears with wrong theoretical hours after change employee calendar

### ISSUE THREAD

**Issue by oriolpiera** [OCA/hr#995]
**Impacted versions:**
12.0

**Steps to reproduce:**

- Install module hr_attendance_report_theoretical_time
- Create and employee with Standard 40h
- Create a leave
- Change working times from Standard 40h 
- Change de date for today+1
- Check report Theoretical vs. worked

**Current behavior:**
It seems that the recompute methods need at least an attendance to be recomputed. But when employees are on holidays, don't register an attendance. So, the employee needs to work an hour in a leave day.

![image](https://user-images.githubusercontent.com/26488435/119871672-faa76600-bf22-11eb-9df5-02085a71e8d9.png)

![image](https://user-images.githubusercontent.com/26488435/119160697-cfbb9e80-ba58-11eb-9088-1feeceb5a7f1.png)
![image](https://user-images.githubusercontent.com/26488435/119161068-2fb24500-ba59-11eb-9b33-01766df47d03.png)

**Comment by oriolpiera** [comment]
The "-1" it wasn't a bug. We figured out.
The employee created the hr.leave (internal date_from 2021-05-14 08:00 to date_to 2021-05-14 17:00).
After that, we changed the "Standard 40h/week working times" to 09:00 to 18:00 hours.
So, all previous leave created, generate a debt in 1 hour (from 17 to 18).
It may be a bug, but I'm not sure that is from this module.

**Comment by pedrobaeza** [comment]
Yes, we considered to recompute leave intervals in #966, but too much cost for the worth of such changes.
